### ISSUE TITLE
scheduler failed to start because ssh-keygen not found

### ISSUE THREAD

**Issue by jacyzon** [paz-sh/paz-scheduler#27]
```
Jun 22 04:39:06 paz bash[21701]: Starting server
Jun 22 04:39:06 paz bash[21701]: sh: ssh-keygen: not found
Jun 22 04:39:06 paz bash[21701]: /usr/src/app/server.js:146
Jun 22 04:39:06 paz bash[21701]: throw new _Error('Error code returned from ssh-keygen: ' + code);
Jun 22 04:39:06 paz bash[21701]: ^
Jun 22 04:39:06 paz bash[21701]: Error: Error code returned from ssh-keygen: 127
Jun 22 04:39:06 paz bash[21701]: at new Server (/usr/src/app/server.js:146:13)
Jun 22 04:39:06 paz bash[21701]: at Object.<anonymous> (/usr/src/app/server.js:191:16)
Jun 22 04:39:06 paz bash[21701]: at Module._compile (module.js:456:26)
Jun 22 04:39:06 paz bash[21701]: at Object.Module._extensions..js (module.js:474:10)
Jun 22 04:39:06 paz bash[21701]: at Module.load (module.js:356:32)
Jun 22 04:39:06 paz bash[21701]: at Function.Module._load (module.js:312:12)
Jun 22 04:39:06 paz bash[21701]: at Function.Module.runMain (module.js:497:10)
Jun 22 04:39:06 paz bash[21701]: at startup (node.js:119:16)
Jun 22 04:39:06 paz bash[21701]: at node.js:906:3
```
#15

The paz-base image does not contains ssh toolkit ([usage](https://github.com/paz-sh/paz-scheduler/blob/2e832ec8f8d036820355cd33a9f2966a10949315/server.js#L144)), either installs it on base image or scheduler image.

``` bash
apk --update add openssh
```

**Comment by sublimino** [comment]
Thanks @jacyzon - looks like there should have been an image-usage test for this, or a full paz integration build running off the back of the previous commit.
