### ISSUE TITLE
paz-scheduler failing to start

### ISSUE THREAD

**Issue by hyperbolic2346** [paz-sh/paz-scheduler#30]
paz-scheduler fails to start for me with the following in the log:

```
Jun 26 05:00:02 wally docker[8333]: 513b7a37b4f1: Download complete
Jun 26 05:00:02 wally systemd[1]: Started paz-scheduler: Takes apps from your paz service directory and runs them on a CoreOS cluster using fleet.
Jun 26 05:00:02 wally bash[8347]: {"port":9002,"loglevel":"info","dbname":"db","svcdir":"paz-service-directory.paz","ssh-host":"10.0.1.22","ssh-key":null,"ssh-port":null,"gen-key":true,"etcd-pubkey-key":"/paz/config/scheduler/_pubkey","etcd-endpoint":"10.0.1.22:4001","cors":true,"nodeploy":false}
Jun 26 05:00:02 wally bash[8347]: Starting server
Jun 26 05:00:02 wally bash[8347]: sh: ssh-keygen: not found
Jun 26 05:00:02 wally bash[8347]: /usr/src/app/server.js:146
Jun 26 05:00:02 wally bash[8347]: throw new _Error('Error code returned from ssh-keygen: ' + code);
Jun 26 05:00:02 wally bash[8347]: ^
Jun 26 05:00:02 wally bash[8347]: Error: Error code returned from ssh-keygen: 127
Jun 26 05:00:02 wally bash[8347]: at new Server (/usr/src/app/server.js:146:13)
Jun 26 05:00:02 wally bash[8347]: at Object.<anonymous> (/usr/src/app/server.js:191:16)
Jun 26 05:00:02 wally bash[8347]: at Module._compile (module.js:456:26)
Jun 26 05:00:02 wally bash[8347]: at Object.Module._extensions..js (module.js:474:10)
Jun 26 05:00:02 wally bash[8347]: at Module.load (module.js:356:32)
Jun 26 05:00:02 wally bash[8347]: at Function.Module._load (module.js:312:12)
Jun 26 05:00:02 wally bash[8347]: at Function.Module.runMain (module.js:497:10)
Jun 26 05:00:02 wally bash[8347]: at startup (node.js:119:16)
Jun 26 05:00:02 wally bash[8347]: at node.js:906:3
```

**Comment by jacyzon** [comment]
duplicate #27 #28

**Comment by hyperbolic2346** [comment]
@jacyzon I apologize. Since it was on the latest version I only looked through the open issues.
